# my custom keybindings for tmux

# move between windows and swap-window 

bind-key -n S-Left previous-window
bind-key -n S-Right next-window
bind-key -n C-S-Left swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right swap-window -t +1\; select-window -t +1

# open new windows and pane on same directory of current pane ! 

bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# disable confirmation from killing windows and panes

bind-key x kill-pane
bind-key & kill-window

bind-key r source-file ~/.config/tmux/tmux.conf; display-message "Reloaded tmux configuration"
bind-key S set-option -g status

# copy-mode don't exit after selecting text in copy emac mode, copy vim mode, and mouse mode
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-no-clear
bind-key -T copy-mode Enter send-keys -X copy-pipe-no-clear
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-no-clear
bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-no-clear

# copy-mode mouse double click select text, copy it and dont exit or clear
bind-key -T copy-mode    DoubleClick1Pane select-pane \; send-keys -X select-word \; run-shell -d 0.3 \; send-keys -X copy-pipe-no-clear
bind-key -T copy-mode-vi DoubleClick1Pane select-pane \; send-keys -X select-word \; run-shell -d 0.3 \; send-keys -X copy-pipe-no-clear
bind-key -T root         DoubleClick1Pane select-pane -t = \; if-shell -F "#{||:#{pane_in_mode},#{mouse_any_flag}}" { send-keys -M } { copy-mode -H ; send-keys -X select-word ; run-shell -d 0.3 ; send-keys -X copy-pipe-no-clear }

# Prefix + P for popup
bind-key P display-popup -w 80% -h 80%
