# Set Ctrl-space as new secondary prefix alongside Ctrl-B
set -g prefix2 C-space

# enable mouse
set -g mouse on

# use vim motions in copy mode
setw -g mode-keys vi

# increase scrolling buffer
set -g history-limit 50000

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Renumber windows when on is deleted
set -g renumber-windows on
