# configuring theme, colours and status bar

# theme
#set -g window-style bg="#232627",fg="#ffffff"
#set -g window-active-style bg="#232627",fg="#ffffff"

# status-bar
set -g status on
set -g status-interval 1

#set -g status-position top
set -g status-style 'bg=#000000,fg=#ffffff'

set -g status-left-length '100'
set -g status-left '[ #S ] '
set -g window-status-current-style 'fg=#000000,bg=#ffffff'
set -g window-status-current-format '#I:#W#F '
set -g window-status-style ''
set -g window-status-format '#I:#W#F '

set -g status-right-length '100'
set -g status-right '#{prefix_highlight} | %H:%M:%S #h '

# tmux_highlight plugin configuration
set -g @prefix_highlight_fg '#000000' # default is 'colour231'
set -g @prefix_highlight_bg '#ffffff' # default is 'colour04'
set -g @prefix_highlight_show_copy_mode 'on'
set -g @prefix_highlight_copy_mode_attr 'fg=#000000,bg=#ffffff,bold' # default is 'fg=default,bg=yellow'
set -g @prefix_highlight_show_sync_mode 'on'
set -g @prefix_highlight_sync_mode_attr 'fg=#000000,bg=#ffffff' # default is 'fg=default,bg=yellow'

#source-file /home/samimbr/.local/lib/python3.13/site-packages/powerline/bindings/tmux/powerline.conf

